const types = {
  string: "[object String]",
  number: "[object Number]",
  function: "[object Function]",
  boolean: "[object Boolean]",
  error: "[object Error]",
  symbol: "[object Symbol]",
  null: "[object Null]",
  undefined: "[object Undefined]",
  date: "[object Date]",
  regExp: "[object RegExp]",
  set: "[object Set]",
  weakSet: "[object WeakSet]",
  map: "[object Map]",
  weakMap: "[object WeakMap]",
  promise: "[object Promise]",
  object: "[object Object]",
  arguments: "[object Arguments]",
  arrayBuffer: "[object ArrayBuffer]",
  array: "[object Array]",
  set: "[object Set]",
  weakSet: "[object WeakSet]",
  map: "[object Map]",
  weakMap: "[object WeakMap]",
};

const typeofValue = {
  boolean: "boolean",
  symbol: "symbol",
  function: "function",
  string: "string",
  number: "number",
  object: "object",
  date: "object",
  error: "object",
  symbol: "symbol",
  arguments: "object",
  arrayBuffer: "object",
  array: "object",
  set: "object",
  weakSet: "object",
  map: "object",
  weakMap: "object",
};

module.exports = { typeofValue, types };
